name: skill_bridge_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_analytics: ^10.6.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dash: ^1.0.0
  flutter_secure_storage: ^8.0.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  flutter_tex: ^4.0.3+4
  get_it: ^7.6.0
  go_router: ^8.0.0
  google_fonts: ^5.0.0
  google_sign_in: ^6.1.5
  http: ^1.0.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  latext: ^0.1.0
  level_map: ^0.2.0
  loading_indicator: ^3.1.0
  omni_datetime_picker: ^1.0.8
  responsive_sizer: ^3.1.1
  scroll_to_index: ^3.0.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.3
  mockito: ^5.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_3.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
