// Mocks generated by Mockito 5.4.4 from annotations
// in skill_bridge_mobile/test/features/department/data/repositories/department_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:skill_bridge_mobile/core/core.dart' as _i4;
import 'package:skill_bridge_mobile/features/features.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DepartmentRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDepartmentRemoteDatasource extends _i1.Mock
    implements _i2.DepartmentRemoteDatasource {
  @override
  _i3.Future<List<_i2.GeneralDepartment>> getAllDepartments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDepartments,
          [],
        ),
        returnValue: _i3.Future<List<_i2.GeneralDepartment>>.value(
            <_i2.GeneralDepartment>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i2.GeneralDepartment>>.value(
                <_i2.GeneralDepartment>[]),
      ) as _i3.Future<List<_i2.GeneralDepartment>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i4.NetworkInfo {
  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [DepartmentLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDepartmentLocalDatasource extends _i1.Mock
    implements _i2.DepartmentLocalDatasource {}
