// Mocks generated by Mockito 5.4.4 from annotations
// in skill_bridge_mobile/test/features/authentication/domain/usecases/change_password_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:skill_bridge_mobile/core/core.dart' as _i5;
import 'package:skill_bridge_mobile/features/authentication/domain/entities/user_credential.dart'
    as _i6;
import 'package:skill_bridge_mobile/features/authentication/domain/repositories/authentication_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i3.AuthenticationRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>> signup({
    required String? emailOrPhoneNumber,
    required String? password,
    required String? firstName,
    required String? lastName,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [],
          {
            #emailOrPhoneNumber: emailOrPhoneNumber,
            #password: password,
            #firstName: firstName,
            #lastName: lastName,
            #otp: otp,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserCredential>(
          this,
          Invocation.method(
            #signup,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #otp: otp,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserCredential>(
          this,
          Invocation.method(
            #signup,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #otp: otp,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>> login({
    required String? emailOrPhoneNumber,
    required String? password,
    required bool? rememberMe,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #emailOrPhoneNumber: emailOrPhoneNumber,
            #password: password,
            #rememberMe: rememberMe,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserCredential>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #password: password,
              #rememberMe: rememberMe,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserCredential>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #password: password,
              #rememberMe: rememberMe,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>> getUserCredential() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCredential,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserCredential>(
          this,
          Invocation.method(
            #getUserCredential,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserCredential>(
          this,
          Invocation.method(
            #getUserCredential,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> changePassword({
    required String? emailOrPhoneNumber,
    required String? newPassword,
    required String? confirmPassword,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #emailOrPhoneNumber: emailOrPhoneNumber,
            #newPassword: newPassword,
            #confirmPassword: confirmPassword,
            #otp: otp,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
              #otp: otp,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #newPassword: newPassword,
              #confirmPassword: confirmPassword,
              #otp: otp,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> forgetPassword({
    required String? emailOrPhoneNumber,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [],
          {
            #emailOrPhoneNumber: emailOrPhoneNumber,
            #otp: otp,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #forgetPassword,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #otp: otp,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #forgetPassword,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #otp: otp,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> sendOtpVerification({
    required String? emailOrPhoneNumber,
    required bool? isForForgotPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtpVerification,
          [],
          {
            #emailOrPhoneNumber: emailOrPhoneNumber,
            #isForForgotPassword: isForForgotPassword,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendOtpVerification,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #isForForgotPassword: isForForgotPassword,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #sendOtpVerification,
            [],
            {
              #emailOrPhoneNumber: emailOrPhoneNumber,
              #isForForgotPassword: isForForgotPassword,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> resendOtpVerification(
          {required String? emailOrPhoneNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendOtpVerification,
          [],
          {#emailOrPhoneNumber: emailOrPhoneNumber},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #resendOtpVerification,
            [],
            {#emailOrPhoneNumber: emailOrPhoneNumber},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #resendOtpVerification,
            [],
            {#emailOrPhoneNumber: emailOrPhoneNumber},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> initializeApp() =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeApp,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #initializeApp,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #initializeApp,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> getAppInitialization() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppInitialization,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #getAppInitialization,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #getAppInitialization,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>> signInWithGoogle() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserCredential>(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserCredential>(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserCredential>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> logoutWithGoogle() =>
      (super.noSuchMethod(
        Invocation.method(
          #logoutWithGoogle,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #logoutWithGoogle,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #logoutWithGoogle,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isAuthenticatedWithGoogle() =>
      (super.noSuchMethod(
        Invocation.method(
          #isAuthenticatedWithGoogle,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isAuthenticatedWithGoogle,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isAuthenticatedWithGoogle,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> storeDeviceToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #storeDeviceToken,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #storeDeviceToken,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #storeDeviceToken,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteDeviceToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDeviceToken,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteDeviceToken,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteDeviceToken,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
