// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-8BywfuPRt7fimj8drp5wnucFTJ75Y-s',
    appId: '1:443488801728:web:62ba61ecd2d235bad1ae25',
    messagingSenderId: '443488801728',
    projectId: 'skillbridge-a947f',
    authDomain: 'skillbridge-a947f.firebaseapp.com',
    storageBucket: 'skillbridge-a947f.appspot.com',
    measurementId: 'G-1V1GSD8QZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKM1OKDVyoL1BCuc2nmPyDFy1o_Q5IfM',
    appId: '1:443488801728:android:60f1b8d8cc074630d1ae25',
    messagingSenderId: '443488801728',
    projectId: 'skillbridge-a947f',
    storageBucket: 'skillbridge-a947f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC52fWYu0_CVExdWbBtSZVNKj09Pan2LwA',
    appId: '1:443488801728:ios:932ed8948f024cb7d1ae25',
    messagingSenderId: '443488801728',
    projectId: 'skillbridge-a947f',
    storageBucket: 'skillbridge-a947f.appspot.com',
    androidClientId: '443488801728-ctlhjv76mqvio5kgjoia6cvop22dhsgk.apps.googleusercontent.com',
    iosClientId: '443488801728-nmtal3b896d8ifpjof8s76akjled2van.apps.googleusercontent.com',
    iosBundleId: 'academy.skillbridge.skillBridgeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC52fWYu0_CVExdWbBtSZVNKj09Pan2LwA',
    appId: '1:443488801728:ios:932ed8948f024cb7d1ae25',
    messagingSenderId: '443488801728',
    projectId: 'skillbridge-a947f',
    storageBucket: 'skillbridge-a947f.appspot.com',
    androidClientId: '443488801728-ctlhjv76mqvio5kgjoia6cvop22dhsgk.apps.googleusercontent.com',
    iosClientId: '443488801728-nmtal3b896d8ifpjof8s76akjled2van.apps.googleusercontent.com',
    iosBundleId: 'academy.skillbridge.skillBridgeMobile',
  );
}
