name: skill_bridge_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+3
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animated_flip_counter: ^0.3.3
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  circle_nav_bar: ^2.0.1+1
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_analytics: ^10.6.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_dynamic_links: ^5.4.14
  firebase_messaging: ^14.7.8
  fl_chart: ^0.68.0
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.2.0
  flutter_localization: ^0.2.0
  flutter_math_fork: ^0.7.2
  flutter_native_splash: ^2.3.8
  flutter_secure_storage: ^8.0.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.0
  go_router: ^8.0.0
  google_fonts: ^5.0.0
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.0.0
  image_picker: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  loading_indicator: ^3.1.0
  markdown_widget: ^2.3.2+2
  pinput: ^4.0.0
  qr_flutter: ^4.1.0
  responsive_sizer: ^3.1.1
  scroll_to_index: ^3.0.1
  share_plus: ^7.2.2
  shimmer: ^3.0.0
  youtube_player_iframe: ^4.0.4
  provider: ^6.1.2
  upgrader: ^10.3.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.3
  hive_generator: ^2.0.1
  mockito: ^5.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_3.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # image: 'assets/images/Logo.png'
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  image: "assets/images/logo_quality.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/bottomNavigation/
    - shorebird.yaml

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

  generate: true
