name: Upload APK to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "birehananteneh4@gmail.com"
          git config --global user.name "GitHub Actions"

      - name: Create Git Tag
        run: git tag -a v1.0.0 -m "Release v1.0.0"  # Replace with the desired version number and release message

      - name: Push Git Tag
        run: git push --force origin v1.0.0  # Replace with the desired version number

      - name: Upload APK to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mobile/build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
