name: Upload APK to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "birehananteneh4@gmail.com"
          git config --global user.name "GitHub Actions"

      - name: Check if Tag Exists
        id: check_tag
        run: git tag -l v1.0.0

      - name: Create Git Tag
        if: steps.check_tag.outputs.stdout == ''
        run: git tag -a v1.0.0 -m "Release v1.0.0"  # Replace with the desired version number and release message

      - name: Push Git Tag
        if: steps.check_tag.outputs.stdout == ''
        run: git push --force origin v1.0.0  # Replace with the desired version number

      - name: Upload APK to Releases
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk

      - name: Display Artifact Link
        run: echo "Download the APK [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/mobile/build/app/outputs/flutter-apk/app-release.apk)"
