name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload APK
        id: upload-release-asset
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk

      - name: Set Release Asset URL
        run: echo "::set-output name=asset_url::${{ steps.upload-release-asset.outputs.artifact_url }}"

      - name: Update Release Description
        run: echo "APK Download: ${{ steps.upload-release-asset.outputs.artifact_url }}" >> $GITHUB_EVENT_PATH

      - name: Update Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{ github.event_path }}
