name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update README with APK link
        run: |
          echo "Download the latest APK [here](https://github.com/${{ github.repository }}/raw/main/mobile/build/app/outputs/flutter-apk/app-release.apk)" >> README.md
          git config user.name "GitHub Actions"
          git config user.email "birehananteneh4@gmail.com"
          git add README.md
          git commit -m "Update README with APK link"
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
