name: Upload APK to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "birehananteneh4@gmail.com"
          git config --global user.name "GitHub Actions"

      - name: Check if Tag Exists
        id: check_tag
        run: git tag -l v1.0.0

      - name: Create Git Tag
        if: steps.check_tag.outputs.stdout == ''
        run: git tag -a v1.0.0 -m "Release v1.0.0"  # Replace with the desired version number and release message

      - name: Push Git Tag
        if: steps.check_tag.outputs.stdout == ''
        run: git push --force origin v1.0.0  # Replace with the desired version number

      - name: Create GitHub Release
        id: create_release
        if: steps.check_tag.outputs.stdout == ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Replace with the desired version number
          release_name: Release v1.0.0  # Replace with the desired release name
          body: Release notes for version 1.0.0  # Replace with release notes

      - name: Upload APK to Releases
        uses: softprops/action-gh-release@v1
        if: steps.check_tag.outputs.stdout == ''
        with:
          files: |
            mobile/build/app/outputs/flutter-apk/app-release.apk
          tag_name: v1.0.0  # Ensure this matches the tag created earlier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
